/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.EditoraDAO;
import controller.AcervoDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Editora;
import model.Acervo;

/**
 *
 * @author bruna
 */
public class CadastroAcervo extends javax.swing.JFrame {

    

    /**
     * Creates new form CadastroAcervo
     */
    public CadastroAcervo() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbxEditora = new javax.swing.JComboBox<>();
        txtTitulo = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        txtQtd = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaLivro = new javax.swing.JTable();
        idLabel = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        labelPesquisar = new javax.swing.JLabel();
        txtPesquisar = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        txtIdEditora = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro de Acervo");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Editora: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Titulo:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Autor:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Ano:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Preço:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("QTD:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Tipo:");

        cbxEditora.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cbxEditora.setToolTipText("");
        cbxEditora.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbxEditoraAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cbxEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEditoraActionPerformed(evt);
            }
        });

        txtTitulo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        txtAutor.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txtAno.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txtPreco.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });

        txtQtd.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txtTipo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnNovo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnNovo.setText("NOVO");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        tabelaLivro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "TITULO", "AUTOR", "ANO", "PREÇO", "QUANTIDADE", "TIPO", "COD EDITORA", "NOME EDITORA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaLivro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaLivroMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaLivro);

        idLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        idLabel.setText("ID:");

        txtId.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        labelPesquisar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelPesquisar.setText("Pesquisar pelo Titulo:");

        txtPesquisar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        btnPesquisar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnPesquisar.setText("PESQUISAR");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        txtIdEditora.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtIdEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdEditoraActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdEditora, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(33, 33, 33)
                        .addComponent(txtAno))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(31, 31, 31)
                        .addComponent(txtQtd))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(32, 32, 32)
                        .addComponent(txtTipo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)
                        .addGap(24, 24, 24)
                        .addComponent(btnNovo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtPreco))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTitulo)
                            .addComponent(txtAutor))))
                .addGap(87, 87, 87))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLabel)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPesquisar)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar)
                    .addComponent(btnNovo)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

       

    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         ListaAcervo();
         estadoControle(true);
    }//GEN-LAST:event_formWindowOpened

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            //instanciar o acervo e a editora
            Acervo acervo = new Acervo();
            Editora editora = new Editora();

            //pegando todos as strings
            acervo.setAutor(txtAutor.getText());
            acervo.setTitulo(txtTitulo.getText());

            //pegando todos os int
            acervo.setAno(Integer.parseInt(txtAno.getText()));
            acervo.setQuantidade(Integer.parseInt(txtQtd.getText()));
            acervo.setTipo(Integer.parseInt(txtTipo.getText()));

            //pegando o double
            acervo.setPreco(Double.parseDouble(txtPreco.getText()));

            //pegando dados da combo box
            editora = (Editora) cbxEditora.getSelectedItem();
            acervo.setObjeditora(editora);

            //chamando o comando INSERT
            AcervoDAO acervoinsert = new AcervoDAO();
            acervoinsert.CadastrarLivro(acervo);

            ListaAcervo();

            LimpaCampos();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void cbxEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEditoraActionPerformed
        
        

    }//GEN-LAST:event_cbxEditoraActionPerformed

    private void tabelaLivroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaLivroMouseClicked
        
        //liberar campos edicao
        estadoControle(false);
        btnEditar.setEnabled(true);
        //pegar os valores das linhas e jogar no txtfield
        txtIdEditora.setText(tabelaLivro.getValueAt(tabelaLivro.getSelectedRow(), 7).toString());
        txtId.setText(tabelaLivro.getValueAt(tabelaLivro.getSelectedRow(), 0).toString());
        txtTitulo.setText(tabelaLivro.getValueAt(tabelaLivro.getSelectedRow(), 1).toString());
        txtAutor.setText(tabelaLivro.getValueAt(tabelaLivro.getSelectedRow(), 2).toString());
        txtAno.setText(tabelaLivro.getValueAt(tabelaLivro.getSelectedRow(), 3).toString());
        txtPreco.setText(tabelaLivro.getValueAt(tabelaLivro.getSelectedRow(), 4).toString());
        txtQtd.setText(tabelaLivro.getValueAt(tabelaLivro.getSelectedRow(), 5).toString());
        txtTipo.setText(tabelaLivro.getValueAt(tabelaLivro.getSelectedRow(), 6).toString());
        
        //pegar valor da cbox
        int id = (int) tabelaLivro.getValueAt(tabelaLivro.getSelectedRow(), 7);
        String nomeEditora = tabelaLivro.getValueAt(tabelaLivro.getSelectedRow(), 8).toString();
        Editora editora = new Editora();
        editora.setIdEditora(id);
        editora.setNomeEditora(nomeEditora);
        cbxEditora.removeAll();
        cbxEditora.getModel().setSelectedItem(editora);
                
        
        //jogar 
    }//GEN-LAST:event_tabelaLivroMouseClicked

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        try {
            
            String titulo = txtPesquisar.getText();
            
            AcervoDAO acervodao = new AcervoDAO();
            
            List<Acervo> listaacervo = acervodao.PesquisarLivroTitulo(titulo);
            
            DefaultTableModel tabelapadrao = (DefaultTableModel) tabelaLivro.getModel();
            tabelapadrao.setNumRows(0);
            
            for (Acervo livro : listaacervo) {
                tabelapadrao.addRow(new Object[] {
                    livro.getIdAcervo(),
                    livro.getTitulo(),
                    livro.getAutor(),
                    livro.getAno(),
                    livro.getPreco(),
                    livro.getQuantidade(),
                    livro.getTipo(),
                    livro.getObjeditora().getIdEditora(),
                    livro.getObjeditora().getNomeEditora(),
                });
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao pesquisar: " + e);
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        estadoControle(false);
        txtId.setEnabled(false);
        txtIdEditora.setEnabled(false);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        try {
            //pegar os dados digitados da tela e colocar em um obj
            Acervo acervo = new Acervo();
            Editora editora = new Editora();

            //pegando os que sao string
            acervo.setTitulo(txtTitulo.getText());
            acervo.setAutor(txtAutor.getText());

            //pegando os que sao int
            acervo.setIdAcervo(Integer.parseInt(txtId.getText()));
            acervo.setAno(Integer.parseInt(txtAno.getText()));
            acervo.setQuantidade(Integer.parseInt(txtQtd.getText()));
            acervo.setTipo(Integer.parseInt(txtTipo.getText()));

            //pegando os que sao double
            acervo.setPreco(Double.parseDouble(txtPreco.getText()));

            //pegar o valor da cbx no campo id
            editora = (Editora) cbxEditora.getSelectedItem();
            acervo.setObjeditora(editora);

            //chamar comando insert 
            AcervoDAO alteraracervo = new AcervoDAO();
            alteraracervo.AtualizarLivro(acervo);

            JOptionPane.showMessageDialog(null, "Registro alterado com sucesso!");
            
            ListaAcervo();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao alterar o registro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        estadoControle(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtIdEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEditoraActionPerformed
        
    }//GEN-LAST:event_txtIdEditoraActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        try {
            
            //pegar o id acervo que esta no campo de texto 
            Acervo acervo = new Acervo();
            
            //passar de string para int
            acervo.setIdAcervo(Integer.parseInt(txtId.getText()));
            
            //chamar o comando DELETE
            AcervoDAO acervodelete = new AcervoDAO();
            acervodelete.ExcluirLivro(acervo);
            
            ListaAcervo();
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao excluir o registro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void cbxEditoraAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbxEditoraAncestorAdded
        // TODO add your handling code here:
        EditoraDAO editoradao = new EditoraDAO();
        
        List<Editora> listaeditora = editoradao.ListarEditora();
        
        cbxEditora.removeAll();
        
        for (Editora editora : listaeditora) {
            cbxEditora.addItem(editora);
        }
    }//GEN-LAST:event_cbxEditoraAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAcervo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAcervo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAcervo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAcervo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CadastroAcervo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<Object> cbxEditora;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelPesquisar;
    private javax.swing.JTable tabelaLivro;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdEditora;
    private javax.swing.JTextField txtPesquisar;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQtd;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables

    private void estadoControle(boolean e) {
        btnSalvar.setEnabled(!e);
        btnCancelar.setEnabled(!e);
        btnEditar.setEnabled(e);
        btnNovo.setEnabled(e);
        btnPesquisar.setEnabled(e);

        cbxEditora.setEnabled(!e);

        txtIdEditora.setEnabled(!e);
        txtId.setEnabled(!e);
        txtTitulo.setEnabled(!e);
        txtAutor.setEnabled(!e);
        txtAno.setEnabled(!e);
        txtPreco.setEnabled(!e);
        txtQtd.setEnabled(!e);
        txtTipo.setEnabled(!e);
        txtPesquisar.setEnabled(e);
    }
    
    public void ListaAcervo(){
        try {
            AcervoDAO acervo = new AcervoDAO();
            
            List<Acervo> listaacervo = acervo.ListarLivro();
            
            DefaultTableModel tabelapadrao = (DefaultTableModel) tabelaLivro.getModel();
            tabelapadrao.setNumRows(0);
            
            for (Acervo livro : listaacervo) {
                tabelapadrao.addRow(new Object[] {
                    livro.getIdAcervo(),
                    livro.getTitulo(),
                    livro.getAutor(),
                    livro.getAno(),
                    livro.getPreco(),
                    livro.getQuantidade(),
                    livro.getTipo(),
                    livro.getObjeditora().getIdEditora(),
                    livro.getObjeditora().getNomeEditora(),
                });
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "erro: " + e);
        }
    }

    private void LimpaCampos() {
       txtId.setText(null);
       txtIdEditora.setText(null);
       txtTitulo.setText(null);
       txtAutor.setText(null);
       txtPreco.setText(null);
       txtQtd.setText(null);
       txtTipo.setText(null);
       txtAno.setText(null);
    }

    
}
